---
name: Build And Deploy
on: [push]
jobs:
  tag:
    name: Tag latest release
    runs-on: ubuntu-latest
    needs:
      - test
      - functional_test
      - e2e_mac
      - e2e_linux
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}

  build_prod:
    name: Build Prod Version
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.tag.outputs.new_tag }}

      - name: Setup Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.147.2
          args: release --rm-dist
          key: ${{ secrets.GPG_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}